version: "3.6"

services:

  annif_app:
    image: quay.io/natlibfi/annif:0.45.3
    command: ["gunicorn", "annif:create_app()", "--bind", "0.0.0.0:8000", "--timeout", "600"]
    volumes:
      - data:/annif-projects
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
        - node.labels.environment == test
      update_config:
        parallelism: 1
        order: start-first
    healthcheck:
      test: ["CMD", "curl", "--fail", "localhost:8000/v1/projects"]
      interval: 15s
      retries: 3
      start_period: 600s

  nginx:
    image: nginx:1.17.7
    volumes:
      - webdata:/webdata
      - /etc/localtime:/etc/localtime:ro
      - logs:/tmp
    command: ["nginx", "-c", "/nginx.conf", "-g", "daemon off;"]
    configs:
      -  nginx.conf
    networks:
      - default
      - traefik-net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
        - node.labels.environment == test
      labels:
        - traefik.enable=true
        - traefik.http.services.annif-test.loadbalancer.server.port=80
        - traefik.http.routers.annif-test-http.rule=Host(`annif.dev.finto.fi`)
        - traefik.http.routers.annif-test-http.entrypoints=http
        - traefik.http.routers.annif-test-http.middlewares=redirect@file
        - traefik.http.routers.annif-test-https.rule=Host(`annif.dev.finto.fi`)
        - traefik.http.routers.annif-test-https.entrypoints=https
        - traefik.http.routers.annif-test-https.tls=true

  mauiserver:
    image: quay.io/natlibfi/mauiserver:1.3.2
    volumes:
      - data:/annif-projects
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MAUI_SERVER_DATA_DIR=/annif-projects/mauidata
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.environment == test

  rsync_client:
    image: quay.io/natlibfi/annif-rsync
    volumes:
      - data:/annif-projects
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - source: annif-rsync-id-rsa
        target: /home/rsync-user/.ssh/id_rsa
        mode: 0400
        uid: '998'
        gid: '998'
      - source: annif-kk-ssh-host-rsa-key
        target: /home/rsync-user/.ssh/known_hosts
        mode: 0600
        uid: '998'
        gid: '998'
    command: rsync -avzLu --exclude '*omikuji-train.txt' annif@128.214.223.211:/srv/annif-data/annif.dev.finto.fi/* /annif-projects
    networks:
      - traefik-net
    deploy:
      replicas: 0
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.environment == test

  webdata_sync:
   image: quay.io/natlibfi/annif-svn
   volumes:
     - webdata:/tmp
     - /etc/localtime:/etc/localtime:ro
   command: svn checkout https://github.com/NatLibFi/Annif/branches/api-instances/annif.dev.finto.fi/ .
   deploy:
     replicas: 1
     restart_policy:
       condition: on-failure
       max_attempts: 3
     placement:
       constraints:
        - node.labels.environment == test

  matomo-importer:
    image: quay.io/natlibfi/annif-logs-matomo-importer
    volumes:
      - logs:/tmp
      - /etc/localtime:/etc/localtime:ro
    command: >
      sh -c "
      tail -f tmp/access.log | python2 import_logs.py --url=***REMOVED*** --idsite=14 --token-auth $$(cat /run/secrets/annif-test-matomo-token) --enable-http-errors --enable-http-redirects --enable-static --enable-bots --recorder-max-payload-size=5 -
      "
    secrets:
      - annif-test-matomo-token
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints:
          - node.labels.environment == test

volumes:
  data:
  webdata:
  logs:

networks:
  traefik-net:
    external: true

configs:
  nginx.conf:
    external: true
    name: annif-test-nginx-proxy3

secrets:
  annif-rsync-id-rsa:
    external: true
  annif-kk-ssh-host-rsa-key:
    external: true
  annif-test-matomo-token:
    external: true
