# This is a values file for helm configuration common to all instances.

timezone: "Europe/Helsinki"

nginx:
  version: '1.20'
  baseImage: 'ubi8'
  git:
    uri: 'https://github.com/NatLibFi/FintoAI.git'
    ref: 'main'
  # TODO Increase storage when project quota allows
  logsStorage : 100Mi

annif:
  version: '0.55.1-ocp'
  resources:
    limits:
      cpu: 1
      memory: 26Gi
  modelDataStorage: 25Gi

matomo:
  serverUrl: '***REMOVED***'
