timezone: "Europe/Helsinki"
cluster: 'test'

annif:
  version: '0.58'
  resources:
    limits:
      cpu: 1
      memory: 20Gi
    requests:
      cpu: 200m
      memory: 5Gi

  modelDataStorage: 2Gi
