apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  http-context.conf: |-
    client_max_body_size 5M;

    log_format matomo '$http_x_forwarded_for - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent"';
    access_log /logs/nginx-access.log matomo;

    upstream annif-app {
        server annif-app:8000;
    }
  server-context.conf: |-
    location /v1/ {
        proxy_pass http://annif-app;
    }
    location ~ \/v1/projects\/([^/]*)\/analyze$ {
        proxy_pass http://annif-app/v1/projects/$1/suggest;
    }
    location ~ \/v1/projects\/([^/]*)\/learn$ {
        deny  all;
    }
---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: ai-finto-fi-nginx
  ports:
  - port: 8080
---

kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ai-finto-fi-nginx
spec:
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nginx:1.16-el7'
  source:
    type: Git
    git:
      uri: 'https://github.com/NatLibFi/Annif.git'
      ref: api-instances
    contextDir: /ai.finto.fi
  output:
    to:
      kind: ImageStreamTag
      name: 'ai-finto-fi-nginx:latest'
  # TODO: Currently GitHub webhooks do not work (cluster disallows connections from outside Internet?).
  # For production instance the below triggers should be anyway removed;
  # the builds should be invoked with "oc start-build ai-finto-fi-nginx"
  triggers:
    - type: GitHub
      github:
        secretReference:
          name: ai-finto-fi-github-webhook-secret
    - type: ImageChange
      imageChange:
        lastTriggeredImageID: >-
          image-registry.openshift-image-registry.svc:5000/openshift/nginx@sha256:2878cf2a32e2bd86b8b00c9349e38f652a2952b47a2f891303ea96c7998b7d34
    - type: ConfigChange
---

kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: ai-finto-fi-nginx
  labels:
    app: ai-finto-fi-nginx
spec:
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - ai-finto-fi-nginx
        from:
          kind: ImageStreamTag
          name: 'ai-finto-fi-nginx:latest'
    - type: ConfigChange
  replicas: 1
  selector:
    app: ai-finto-fi-nginx
    deploymentconfig: ai-finto-fi-nginx
  template:
    metadata:
      labels:
        app: ai-finto-fi-nginx
        deploymentconfig: ai-finto-fi-nginx
    spec:
      containers:
        - name: ai-finto-fi-nginx
          # Should the image below be specified with a hash, or is "latest" enough?
          image: >-
            image-registry.openshift-image-registry.svc:5000/annif/ai-finto-fi-nginx:latest
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /index.html
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          volumeMounts:
            - name: nginx-conf
              mountPath: /opt/app-root/etc/nginx.d/http-context.conf
              subPath: http-context.conf
            - name: nginx-conf
              mountPath: /opt/app-root/etc/nginx.default.d/server-context.conf
              subPath: server-context.conf
            - name: logs
              mountPath: /logs
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
        - name: logs
          persistentVolumeClaim:
            claimName: logs
            readOnly: False
---

apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ai-finto-fi-nginx
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: annif
  labels:
    type: external
spec:
  host: {{ .Values.host}}
  port:
    targetPort: 8080
  to:
    kind: Service
    name: nginx
  wildcardPolicy: None
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
