kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.instance }}-model-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.annifModelDataStorage }}
