apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.instance }}-annif
  labels:
    app.kubernetes.io/instance: {{ .Values.instance }}
spec:
  selector:
    app.kubernetes.io/name: annif
    app.kubernetes.io/instance: {{ .Values.instance }}
  ports:
  - port: 8000
