apiVersion: v1
kind: Service
metadata:
  name: annif-app
spec:
  selector:
    app: annif-app
  ports:
  - port: 8000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: annif-app
  name: annif-app
spec:
  selector:
    matchLabels:
      app: annif-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: annif-app
    spec:
      containers:
        - image: quay.io/natlibfi/annif:0.52
          command: ["gunicorn", "annif:create_app()", "--bind", "0.0.0.0:8000", "--timeout", "600"]
          livenessProbe:
            exec:
              command: ["curl", "--fail", "localhost:8000/v1/projects"]
            failureThreshold: 3
            initialDelaySeconds: 600
            periodSeconds: 15
          name: annif-app
          resources:
            limits:
              cpu: 2  # TODO Check if cpu limit can be decreased, to 1 maybe
              memory: 26Gi
          volumeMounts:
            - mountPath: /annif-projects
              name: model-data
              # TODO: Switch to readOnly, if model syncing method allows.
              #readOnly: true
      volumes:
        - name: model-data
          persistentVolumeClaim:
            claimName: model-data
            readOnly: true
---

# TODO Include this PVC?
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: model-data
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 25Gi
