apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}
  labels:
    type: external
    app.kubernetes.io/instance: {{ .Release.Namespace }}
spec:
  host: dev.annif.org
  port:
    targetPort: 8000
  to:
    kind: Service
    name: {{ .Release.Name }}-annif
  wildcardPolicy: None
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
