apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: annif-app
  name: {{ .Values.instance }}-annif-app
spec:
  selector:
    matchLabels:
      app: annif-app
  strategy:
    # TODO: Switch to type: Rolling if there's enough memory for two simultaneously runnig apps
    type: Recreate
  template:
    metadata:
      labels:
        app: annif-app
    spec:
      containers:
        - image: quay.io/natlibfi/annif:{{ .Values.annifVersion }}
          command: ["gunicorn", "annif:create_app()", "--bind", "0.0.0.0:8000", "--timeout", "600"]
          livenessProbe:
            exec:
              command: ["curl", "--fail", "localhost:8000/v1/projects"]
            failureThreshold: 3
            initialDelaySeconds: 600
            periodSeconds: 15
          name: annif-app
          resources:
            {{ toYaml .Values.annifResources | nindent 12 }}
          volumeMounts:
            - mountPath: /annif-projects
              name: model-data
              # TODO: Switch to readOnly, if model syncing method allows.
              #readOnly: true
      volumes:
        # TODO: Separate volumes for each instance
        - name: model-data
          persistentVolumeClaim:
            claimName: model-data
            readOnly: true
