kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
  name: {{ .Release.Name }}-matomo-log-analytics
  labels:
    app.kubernetes.io/name: matomo-log-analytics
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: '{{ .Release.Name }}-matomo-log-analytics:latest'
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'python:3.8-ubi7'
  source:
    type: Git
    git:
      uri: 'https://github.com/NatLibFi/matomo-log-analytics'
  triggers:
    - type: GitHub
      github:
        secretReference:
          name: matomo-log-analytics-github-webhook-secret
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
  runPolicy: Serial
