kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-matomo-log-analytics
  labels:
    app.kubernetes.io/name: matomo-log-analytics
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: matomo-log-analytics
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: matomo-log-analytics
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      # TODO Add init-containers to clear logs?
      containers:
        - name: matomo-log-analytics
          image: >-
            image-registry.openshift-image-registry.svc:5000/annif/{{ .Release.Name }}-matomo-log-analytics:latest
          command: ["/bin/sh", "-c"]
          args:
            - tail -f /logs/nginx-access.log | python /opt/app-root/src/import_logs.py
              --url=$(MATOMO-SERVER-URL)
              --idsite={{ .Values.matomo.siteId}}
              --token-auth $(MATOMO-TOKEN)
              --enable-http-errors
              --enable-http-redirects
              --enable-static
              --enable-bots
              --track-http-method true
              --recorder-max-payload-size=10 -
          env:
            - name: TZ
              value: {{ .Values.timezone }}
            # Secrets are managed in OpenShift webUI
            - name: MATOMO-TOKEN
              valueFrom:
                secretKeyRef:
                  name: matomo
                  key: token
            - name: MATOMO-SERVER-URL
              valueFrom:
                secretKeyRef:
                  name: matomo
                  key: server-url
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: logs
              mountPath: /logs
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-logs
            readOnly: True
      # Matomo script needs to be run on the same node as nginx:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: nginx
                app.kubernetes.io/instance: {{ .Release.Name }}
            topologyKey: kubernetes.io/hostname
