kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.instance }}-matomo-log-analytics
  labels:
    app.kubernetes.io/name: matomo-log-analytics
    app.kubernetes.io/instance: {{ .Values.instance }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: matomo-log-analytics
      app.kubernetes.io/instance: {{ .Values.instance }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: matomo-log-analytics
        app.kubernetes.io/instance: {{ .Values.instance }}
    spec:
      # TODO Add init-containers to clear logs?
      containers:
        - name: matomo-log-analytics
          image: >-
            image-registry.openshift-image-registry.svc:5000/annif/{{ .Values.instance }}-matomo-log-analytics:latest
          command: ["/bin/sh", "-c"]
          args:
            - tail -f /logs/nginx-access.log | python /opt/app-root/src/import_logs.py
              --url={{ .Values.matomo.serverUrl }}
              --idsite={{ .Values.matomo.siteId}}
              --token-auth $(MATOMO-TOKEN)
              --enable-http-errors
              --enable-http-redirects
              --enable-static
              --enable-bots
              --track-http-method true
              --recorder-max-payload-size=10 -
          env:
            # Secret is managed in OpenShift webUI
            - name: MATOMO-TOKEN
              valueFrom:
                secretKeyRef:
                  name: matomo-token
                  key: matomo-token
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: logs
              mountPath: /logs
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: {{ .Values.instance }}-logs
            readOnly: True
      # Matomo script needs to be run on the same node as nginx:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Values.instance }}-nginx
            topologyKey: kubernetes.io/hostname
