apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.instance }}-nginx-conf
  labels:
    app.kubernetes.io/instance: {{ .Values.instance }}
data:
  http-context.conf: |-
    client_max_body_size 5M;

    log_format matomo '$http_x_forwarded_for - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent"';
    access_log /logs/nginx-access.log matomo;

    upstream annif-app {
        server {{ .Values.instance }}-annif-app:8000;
    }
  server-context.conf: |-
    location /v1/ {
        proxy_pass http://annif-app;
    }
    location ~ \/v1/projects\/([^/]*)\/analyze$ {
        proxy_pass http://annif-app/v1/projects/$1/suggest;
    }
    location ~ \/v1/projects\/([^/]*)\/learn$ {
        deny  all;
    }
