kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ .Values.instance }}-nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: {{ .Values.instance }}
spec:
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nginx:{{ .Values.nginx.version }}-{{ .Values.nginx.baseImage }}'
  source:
    type: Git
    git:
      {{ toYaml .Values.nginx.git | nindent 6 }}
    contextDir: {{ .Values.nginx.contextDir }}
  output:
    to:
      kind: ImageStreamTag
      name: '{{ .Values.instance }}-nginx:latest'
  triggers:
    {{ toYaml .Values.nginx.buildTriggers | nindent 4 }}
