apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-conf
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  http-context.conf: |-
    client_max_body_size 5M;

    log_format matomo '$http_x_forwarded_for - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent"';
    access_log /logs/nginx-access.log matomo;

    upstream annif {
        server {{ .Release.Name }}-annif:8000;
    }
    upstream textract {
        server {{ .Release.Name }}-textract:{{ .Values.textract.port }};
    }
  server-context.conf: |-
    location /v1/ {
        proxy_pass http://annif;
    }
    location ~ \/v1/projects\/([^/]*)\/analyze$ {
        proxy_pass http://annif/v1/projects/$1/suggest;
    }
    location ~ \/v1/projects\/([^/]*)\/learn$ {
        deny  all;
    }
    location /textract {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 55M;
        proxy_pass http://textract;
    }
