apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}
  labels:
    type: external
    app.kubernetes.io/instance: {{ .Release.Namespace }}
spec:
  # TODO: Drop the OCP name part
  host: {{ .Release.Name | replace "-" "."}}.ext.ocp-kk-{{ .Values.cluster }}-0.k8s.it.helsinki.fi
  port:
    targetPort: 8080
  to:
    kind: Service
    name: {{ .Release.Name }}-nginx
  wildcardPolicy: None
