kind: DeploymentConfig  # TODO Switch to Deployment?
apiVersion: apps.openshift.io/v1
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.nginx.version | quote }}
spec:
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - nginx
        from:
          kind: ImageStreamTag
          name: '{{ .Release.Name }}-nginx:latest'
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - matomo-log-analytics
        from:
          kind: ImageStreamTag
          namespace: annif
          name: '{{ .Release.Name }}-matomo-log-analytics:latest'
    - type: ConfigChange
  replicas: 1
  selector:
    app.kubernetes.io/name: nginx
    deploymentconfig: {{ .Release.Name }}-nginx
  template:
    metadata:
      labels:
        deploymentconfig: {{ .Release.Name }}-nginx
        app.kubernetes.io/name: nginx
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Values.nginx.version | quote }}
    spec:
      containers:

        - name: nginx
          image: >-
            image-registry.openshift-image-registry.svc:5000/annif/{{ .Release.Name }}-nginx:latest
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /index.html
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 60
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          volumeMounts:
            - name: nginx-conf
              mountPath: /opt/app-root/etc/nginx.d/http-context.conf
              subPath: http-context.conf
            - name: nginx-conf
              mountPath: /opt/app-root/etc/nginx.default.d/server-context.conf
              subPath: server-context.conf
            - name: logs
              mountPath: /logs
          env:
            - name: TZ
              value: {{ .Values.timezone }}

        - name: matomo-log-analytics
          image: >-
            image-registry.openshift-image-registry.svc:5000/annif/{{ .Release.Name }}-matomo-log-analytics:latest
          command: ["/bin/sh", "-c"]
          args:
            - tail -f /logs/nginx-access.log | python /opt/app-root/src/import_logs.py
              --url=$(MATOMO-SERVER-URL)
              --idsite={{ .Values.matomo.siteId}}
              --token-auth $(MATOMO-TOKEN)
              --enable-http-errors
              --enable-http-redirects
              --enable-static
              --enable-bots
              --track-http-method true
              --recorder-max-payload-size=10 -
          env:
            - name: TZ
              value: {{ .Values.timezone }}
            # Secrets are managed in OpenShift webUI
            - name: MATOMO-TOKEN
              valueFrom:
                secretKeyRef:
                  name: matomo
                  key: token
            - name: MATOMO-SERVER-URL
              valueFrom:
                secretKeyRef:
                  name: matomo
                  key: server-url
          volumeMounts:
            - name: logs
              mountPath: /logs

      volumes:
        - name: nginx-conf
          configMap:
            name: {{ .Release.Name }}-nginx-conf
        - name: logs
          emptyDir:
