kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.nginx.version | quote }}
spec:
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - {{ .Release.Name }}-nginx
        from:
          kind: ImageStreamTag
          name: '{{ .Release.Name }}-nginx:latest'
    - type: ConfigChange
  replicas: 1
  selector:
    app.kubernetes.io/name: nginx
    deploymentconfig: {{ .Release.Name }}-nginx
  template:
    metadata:
      labels:
        deploymentconfig: {{ .Release.Name }}-nginx
        app.kubernetes.io/name: nginx
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Values.nginx.version | quote }}
    spec:
      containers:
        - name: {{ .Release.Name }}-nginx
          image: >-
            image-registry.openshift-image-registry.svc:5000/annif/{{ .Release.Name }}-nginx:latest
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /index.html
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 60
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          volumeMounts:
            - name: nginx-conf
              mountPath: /opt/app-root/etc/nginx.d/http-context.conf
              subPath: http-context.conf
            - name: nginx-conf
              mountPath: /opt/app-root/etc/nginx.default.d/server-context.conf
              subPath: server-context.conf
            - name: logs
              mountPath: /logs
          env:
            - name: TZ
              value: {{ .Values.timezone }}
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ .Release.Name }}-nginx-conf
        - name: logs
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-logs
            readOnly: False
