kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.instance }}-textract
  labels:
    app.kubernetes.io/name: textract
    app.kubernetes.io/instance: {{ .Values.instance }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: textract
      app.kubernetes.io/instance: {{ .Values.instance }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: textract
        app.kubernetes.io/instance: {{ .Values.instance }}
    spec:
      containers:
        - name: textract
          image: >-
            image-registry.openshift-image-registry.svc:5000/annif/{{ .Values.instance }}-textract:latest
          livenessProbe:
            exec:
              command: ["curl", "--fail", "localhost:{{ .Values.textract.port }}/status"]
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 15
          env:
            - name: PORT
              value: {{ quote .Values.textract.port }}
            - name: TZ
              value: {{ .Values.timezone }}
          ports:
            - containerPort: {{ .Values.textract.port }}
              protocol: TCP
